site_name: Alvin Li
site_description: Logistics, Infrastructure, Precision in Motion
site_url: https://www.alvinli.com
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tracking
    - content.code.copy
    - content.action.edit
    - search.suggest
  palette:
    - scheme: default
      primary: black
      accent: blue
    - scheme: slate
      primary: black
      accent: blue
plugins:
  - search
  - minify
  - glightbox
markdown_extensions:
  - attr_list
  - md_in_html
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alvin-li-596a3316a/
nav:
  - Home: index.md
  - Aviation:
      - Overview: aviation/index.md
  - Rail: 
      - Overview: rail/index.md
      - InnoTrans 2024 Cabin: rail/innotrans-2024.md
      - Rail Engineering: rail/stadler-2023.md
      - Rail Acoustics: rail/door-2023.md
      - Ã–BB Seats: rail/obb-2024.md
      - E5 x E6 Coupling: rail/e5e6.md
      - E5 Shinkansen Seikan Tunnel: rail/e5skn.md
      - E5 DOor Sequencing: rail/e5close.md
  - Automation:
      - Overview: automation/index.md
      - ABB Flexley + Cambrian: automation/abb-flexley-cambrian.md
      - Airport Baggage Flow (Tecnomatix): automation/airport-baggage-tecnomatix.md
  - Infrastructure: 
      - Overview: infrastructure/index.md
  - Reflections:
      - Overview: reflections/index.md
  - About: about.md
